# Notebook 07 - 🐼 Pandas: Tu superpoder para Analizar Datos

## AUTOR: KEVIN MADRIGAL BUSTAMANTE
### **FECHA: 20/07/2026**



> NOTA: Compartir con ajmena92@gmail.com



Con Pandas podemos extraer informacion directa desde:
*   CSV
*   JSON
*   HTML y mas

In [ ]:
#EXTRACCION
import pandas as pd # Importar libreria de pandas

url_bccr = "https://gee.bccr.fi.cr/IndicadoresEconomicos/Cuadros/frmConsultaTCVentanilla.aspx"

tablas_web = pd.read_html(url_bccr, encoding='UTF-8', decimal=",", thousands=".") # read_html() devuelve el contenido del sitio
print("Tipo de datos de tabla web:", type(tablas_web))
print("Numero de tablas encontradas:", len(tablas_web))

df = tablas_web[2].copy()
# Analisis
print("")
print(df.info())
print("")

print("\n---DIMENSIONES---")
print(df.shape)
df.head()

Tipo de datos de tabla web: <class 'list'>
Numero de tablas encontradas: 8

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       8 non-null      object
 1   1       38 non-null     object
 2   2       38 non-null     object
 3   3       38 non-null     object
 4   4       38 non-null     object
 5   5       38 non-null     object
dtypes: object(6)
memory usage: 2.0+ KB
None


---DIMENSIONES---
(39, 6)

,0,1,2,3,4,5
0,Tipo de Entidad,Entidad Autorizada,Compra,Venta,Diferencial Cambiario,Última Actualización
1,Bancos públicos,Banco de Costa Rica,444.00,458.00,14.00,20/07/2026 03:59 p.m.
2,NaN,Banco Nacional de Costa Rica,444.00,458.00,14.00,20/07/2026 02:18 p.m.
3,NaN,Banco Popular y de Desarrollo Comunal,444.00,458.00,14.00,20/07/2026 01:27 p.m.
4,Bancos privados,Banco BAC San José S.A.,444.00,458.00,14.00,20/07/2026 01:22 p.m.

## 🧹 Limpieza y Transformación (La Evolución de Nuestro ETL Robusto)

Recordarás la importancia de la limpieza y saneamiento de datos del Notebook 06. Pandas no solo lo hace más fácil, sino que también nos da herramientas mucho más potentes para manejar los datos sucios del mundo real (valores faltantes, errores de formato, etc.).

In [ ]:
# Eliminar Valores Nulos
df.dropna()

,0,1,2,3,4,5
0,Tipo de Entidad,Entidad Autorizada,Compra,Venta,Diferencial Cambiario,Última Actualización
1,Bancos públicos,Banco de Costa Rica,444.00,458.00,14.00,20/07/2026 03:59 p.m.
4,Bancos privados,Banco BAC San José S.A.,444.00,458.00,14.00,20/07/2026 01:22 p.m.
14,Financieras,Financiera Cafsa S.A.,440.00,458.00,18.00,20/07/2026 02:21 p.m.
17,Mutuales de Vivienda,Grupo Mutual Alajuela - La Vivienda de Ahorro ...,443.00,458.00,15.00,20/07/2026 03:28 p.m.
19,Cooperativas,Coope-ANDE N°1 R.L.,445.00,459.50,14.50,14/07/2026 11:43 a.m.
27,Casas de Cambio,Airpak Casa de Cambio,447.00,465.00,18.00,19/07/2026 02:26 a.m.
32,Puestos de Bolsa,"BCT Valores, Puesto De Bolsa, S.A.",440.00,458.00,18.00,20/07/2026 01:17 p.m.

In [ ]:
# Rellenar valores nulos
df.fillna("No Valor")
df.head(3)

,0,1,2,3,4,5
0,Tipo de Entidad,Entidad Autorizada,Compra,Venta,Diferencial Cambiario,Última Actualización
1,Bancos públicos,Banco de Costa Rica,444.00,458.00,14.00,20/07/2026 03:59 p.m.
2,NaN,Banco Nacional de Costa Rica,444.00,458.00,14.00,20/07/2026 02:18 p.m.

In [ ]:
# Reemplazar nulos con el ultimo valor hasta que aparezca uno diferente
# df = df.ffill()
df.ffill(inplace=True)

In [ ]:
# Encabezados
# Extraer la primera fila
primera_fila = df.iloc[0]

# ASIGNAR al DF la primera fila como columnas
df.columns = primera_fila
df.head(3)

# Eliminar la serie (fila) 0, la duplicada
df.drop(0, inplace=True)
df.tail(3)

,Tipo de Entidad,Entidad Autorizada,Compra,Venta,Diferencial Cambiario,Última Actualización
36,Puestos de Bolsa,"Popular Valores, Puesto de Bolsa",443.00,457.00,14.00,20/07/2026 08:12 a.m.
37,Puestos de Bolsa,PRIVAL Securities Puesto de Bolsa S.A,442.00,456.00,14.00,20/07/2026 09:18 a.m.
38,Puestos de Bolsa,PRIVAL Securities Puesto de Bolsa S.A,442.00,456.00,14.00,20/07/2026 09:18 a.m.

In [ ]:
# Renombrar columnas
df.rename(columns={"Tipo de Entidad": "TIPO", "Entidad Autorizada": "ENTIDAD", "Compra": "COMPRA", "Venta": "VENTA", "Diferencial Cambiario": "DIFERENCIAL", "Última Actualización": "FECHA"}, inplace=True)
df.head()

,TIPO,ENTIDAD,COMPRA,VENTA,DIFERENCIAL,FECHA
1,Bancos públicos,Banco de Costa Rica,444.00,458.00,14.00,20/07/2026 03:59 p.m.
2,Bancos públicos,Banco Nacional de Costa Rica,444.00,458.00,14.00,20/07/2026 02:18 p.m.
3,Bancos públicos,Banco Popular y de Desarrollo Comunal,444.00,458.00,14.00,20/07/2026 01:27 p.m.
4,Bancos privados,Banco BAC San José S.A.,444.00,458.00,14.00,20/07/2026 01:22 p.m.
5,Bancos privados,Banco BCT S.A.,440.00,458.00,18.00,20/07/2026 01:02 p.m.

In [ ]:
# Eliminar duplicados
df.drop_duplicates(inplace=True)
df.tail()

,TIPO,ENTIDAD,COMPRA,VENTA,DIFERENCIAL,FECHA
33,Puestos de Bolsa,"BN Valores S.A., Puesto de Bolsa",442.00,456.00,14.00,20/07/2026 08:19 a.m.
34,Puestos de Bolsa,Mercado Valores de Costa Rica Puesto de Bolsa,440.00,458.00,18.00,14/07/2026 01:01 p.m.
35,Puestos de Bolsa,PB Inversiones SAMA,442.00,456.00,14.00,20/07/2026 07:23 a.m.
36,Puestos de Bolsa,"Popular Valores, Puesto de Bolsa",443.00,457.00,14.00,20/07/2026 08:12 a.m.
37,Puestos de Bolsa,PRIVAL Securities Puesto de Bolsa S.A,442.00,456.00,14.00,20/07/2026 09:18 a.m.

In [ ]:
# Tipado de series en el DataFrame (Conversion)
columnas_float = ["COMPRA", "VENTA", "DIFERENCIAL"]
#df[columnas_float].apply(pd.to_numeric, inplace=True)
df[columnas_float] = df[columnas_float].astype(float, errors='ignore')

df["FECHA"].apply(pd.to_datetime, dayfirst=True, errors='coerce')
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 37 entries, 1 to 37
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   TIPO         37 non-null     object
 1   ENTIDAD      37 non-null     object
 2   COMPRA       37 non-null     float64
 3   VENTA        37 non-null     float64
 4   DIFERENCIAL  37 non-null     float64
 5   FECHA        37 non-null     object
dtypes: float64(3), object(3)
memory usage: 3.1+ KB

In [ ]:
# Carlos gana en $, quiere saber que entidad paga mas
tipo_compra_max = df["COMPRA"].max()


filtro = df["COMPRA"] == tipo_compra_max
lista_entidades = df[filtro]
print(f"La entidad que mas paga es: \n{lista_entidades['ENTIDAD']} con un valor de: {lista_entidades['COMPRA']}")

La entidad que mas paga es:
28    ARI Casa de Cambio Internacional S.A.
Name: ENTIDAD, dtype: object con un valor de: 28    448.1
Name: COMPRA, dtype: float64

In [ ]:
# Carlos gana en dolares, quieres saber que entidad paga mas
tipo_compra_max = df['COMPRA'].max()
print(tipo_compra_max)
#lista_entidades = df[df['COMPRA'] == tipo_compra_max]['ENTIDAD'].tolist()
filtro = df['COMPRA'] == tipo_compra_max
lista_entidades = df[filtro]
print(f"La entidad que paga mas: {lista_entidades['ENTIDAD'].values} con un valor de: {lista_entidades['COMPRA']}")
#

448.1
La entidad que paga mas: ['ARI Casa de Cambio Internacional S.A.'] con un valor de: 28    448.1
Name: COMPRA, dtype: float64

In [ ]:
df.groupby("TIPO")["VENTA"].describe()
#

,count,mean,std,min,25%,50%,75%,max
TIPO,,,,,,,,
Bancos privados,10.0,457.900000,1.523884,457.00,457.0,457.5,458.000,462.00
Bancos públicos,3.0,458.000000,0.000000,458.00,458.0,458.0,458.000,458.00
Casas de Cambio,5.0,489.618000,39.012068,453.97,465.0,465.0,531.000,533.12
Cooperativas,8.0,458.687500,1.334635,457.00,458.0,458.0,459.625,461.00
Financieras,3.0,457.666667,3.511885,454.00,456.0,458.0,459.500,461.00
Mutuales de Vivienda,2.0,457.000000,1.414214,456.00,456.5,457.0,457.500,458.00
Puestos de Bolsa,6.0,456.833333,0.983192,456.00,456.0,456.5,457.750,458.00